// Code generated by command: go run asm.go -out axpy_amd64.s -stubs axpy_amd64.go -testhelp axpy_amd64_stub_test.go. DO NOT EDIT.

package compare

func AxpyPointer_V0A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V0A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V1A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V2A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V3A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointer_V4A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V0A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V1A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V2A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V3A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyPointerLoop_V4A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A0(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A1(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A2(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A3(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A4(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A5(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A6(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A7(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A8(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A9(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A10(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A11(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A12(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A13(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A14(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A15(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V0A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V1A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V2A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V3A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)

func AxpyUnsafe_V4A16(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)
