// Code generated by command. DO NOT EDIT.

package compare

type axpyDecl struct {
	name string
	fn   func(alpha float32, xs *float32, incx uintptr, ys *float32, incy uintptr, n uintptr)
}

var axpyDecls = []axpyDecl{
	{name: "AxpyPointer_A8", fn: AxpyPointer_A8},
	{name: "AxpyPointer_A9", fn: AxpyPointer_A9},
	{name: "AxpyPointer_A10", fn: AxpyPointer_A10},
	{name: "AxpyPointer_A11", fn: AxpyPointer_A11},
	{name: "AxpyPointer_A12", fn: AxpyPointer_A12},
	{name: "AxpyPointer_A13", fn: AxpyPointer_A13},
	{name: "AxpyPointer_A14", fn: AxpyPointer_A14},
	{name: "AxpyPointer_A15", fn: AxpyPointer_A15},
	{name: "AxpyPointer_A16", fn: AxpyPointer_A16},
	{name: "AxpyPointerLoop_A8", fn: AxpyPointerLoop_A8},
	{name: "AxpyPointerLoop_A9", fn: AxpyPointerLoop_A9},
	{name: "AxpyPointerLoop_A10", fn: AxpyPointerLoop_A10},
	{name: "AxpyPointerLoop_A11", fn: AxpyPointerLoop_A11},
	{name: "AxpyPointerLoop_A12", fn: AxpyPointerLoop_A12},
	{name: "AxpyPointerLoop_A13", fn: AxpyPointerLoop_A13},
	{name: "AxpyPointerLoop_A14", fn: AxpyPointerLoop_A14},
	{name: "AxpyPointerLoop_A15", fn: AxpyPointerLoop_A15},
	{name: "AxpyPointerLoop_A16", fn: AxpyPointerLoop_A16},
	{name: "AxpyUnsafe_A8", fn: AxpyUnsafe_A8},
	{name: "AxpyUnsafe_A9", fn: AxpyUnsafe_A9},
	{name: "AxpyUnsafe_A10", fn: AxpyUnsafe_A10},
	{name: "AxpyUnsafe_A11", fn: AxpyUnsafe_A11},
	{name: "AxpyUnsafe_A12", fn: AxpyUnsafe_A12},
	{name: "AxpyUnsafe_A13", fn: AxpyUnsafe_A13},
	{name: "AxpyUnsafe_A14", fn: AxpyUnsafe_A14},
	{name: "AxpyUnsafe_A15", fn: AxpyUnsafe_A15},
	{name: "AxpyUnsafe_A16", fn: AxpyUnsafe_A16},
}
